### ISSUE TITLE
Should we make Modes and game results optional?

### ISSUE THREAD

**Issue by jessebmiller** [SetMatchGames/squad#4]
There are interesting games that don't really have results, like MMOs, RPGs, and Single Player Games.

Each of these could be coerced into having some representation of a game result, but that seems unnecessary.

We could even make them part of the game (which I think we have considered before, but like the idea of having them reusable across games).

**Comment by EzraWeller** [comment]
Yeah, I would even say components and formats are technically optional as well: we could allow someone to create a full RPG that doesn't have any identifiable components (to which they could add components later?). So the only thing a game really needs to be valid is a "game" element.

**Comment by jessebmiller** [comment]
Sure that makes sense.

so whatever launches a game should take an `Option<Mode>` and an `Option<Format>` (if it's in rust)

**Comment by jessebmiller** [comment]
So this leads to a next level of the question. If they are optional, should they be external and independent?

Should squad know about them at all or is it architected in a way that any independent third party could, if they wanted to, hook into the system and build Modes and game results (or other abstractions). This could be us but later.

The benefit of doing it this way would be a less complex squad implementation

**Comment by EzraWeller** [comment]
Hmm, one interesting point is that the curation markets will want to use some standard game result data, so we might want to have some kind of MVP game result and mode(s) that every game must be compatible with that can feed into the curation system -- for sure, I as a player would want to sort games by how popular they are (i.e. how many games have been played), for example.

Maybe squad should implement some standard game results and modes for sorting through games and components, but custom game results and modes can be external and independent. My guess is that it won't be that useful to sort through (i.e. have curation markets for) modes and game results directly in squad, since those will mostly be game specific.

**Comment by jessebmiller** [comment]
I'd be a little worried engineering in any methods we think the market will care about. I think we can seed the market with examples and precedents with our own early games and the data those publish, perhaps with a system that other games can join if they choose, but I think the market will demand what it demands from game developers and reward publishing the data it wants.

**Comment by jessebmiller** [comment]
The main thing for me is that they are as decoupled as possible, meaning that modes and game results are at least outside of the elements zome, and probably a plugin of one kind or another.
